### ISSUE TITLE
Bug in HistoryCorrect

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#108]
When I call this method on wrapper "updated" returns always 0 even I can see on admin that history was corrected. 

virtual int          __stdcall HistoryCorrect(LPCSTR symbol,int *updated)             =0;

**Comment by Uriil** [comment]
Sorry, but I have no idea, never used it

**Comment by miho99** [comment]
the updated should be passed as a ref. Since int is a primitive it always returns 0.

**Comment by Uriil** [comment]
Okay, got your point and think you are right. Will update it during next few days

**Comment by Uriil** [comment]
Hi,

I've pushed changes to dev branch. Unfortunatly I had to change method signature because there is no equivalent to ref in C++/CLI.

So in case of error exception will be thrown.

Other way I will return updated count. 

Please check and let me know if it works correctly

**Comment by miho99** [comment]
Here you go

```
int P23::MetaTrader4::Manager::ClrWrapper::HistoryCorrect(String^ symbol, int% updated)
{
	int updatedBars = updated;
	
	int result = _manager->Manager->HistoryCorrect(Convert(symbol), &updatedBars);
	updated = updatedBars;

	return result;
}
```

**Comment by Uriil** [comment]
Thank you, but I think I will stay with current implementation, to be
consistent in wrapper.

**Comment by miho99** [comment]
again you change the original manager api signatures. This is not correct. Trading needs high performance apps. Throwing exceptions where not needed is very very expensive and decreases performance.

**Comment by Uriil** [comment]
I understand your point of you. However error codes decrease level of readability. 

About performance? Here ERROR is something unexpected and not a part of normal flow(or am I wrong?).

What you going to do in case of exception? You will have to interrupt your workflow, probably reconnect or even debug and issue. This exception won't be rised tens or hundreds time per second, so performance impact will be small.

According to Microsoft [guidelines on exception](https://msdn.microsoft.com/en-us/library/ms229030(v=vs.110).aspx), we should not return error codes.

I agreed one exception in MarginLevelGet, because it was prat of normal flow.

**Comment by miho99** [comment]
I dont agree changing the method signatures of the Man API. I will fork the repo and follow Manager API signatures.

Thanks.

**Comment by miho99** [comment]
Introducing custom logic with exceptions etc.. make it difficult to maintain to Metaquotes changes

**Comment by Uriil** [comment]
Once again, I understand your point of view. But there are some differences. For example events for extended pumping, variable names, naming conventions.

There are still places, where I don't agree with metaquotes structure (TradeTransaction is one of examples), but I keep it, because change would be huge and inconvenient for everyone.

I am keeping it as close as possible, but if something inside goes against .Net practices I am changing it a bit.

I am using this library and it's ancestor for 6 years, and in case of those error codes I was always throwing exception, but one level above.(I agree, that in case of marginerrorget, exception was a bug in one particular case).

I am really sorry for this argue, and your feedback was always valuable for.

**Comment by miho99** [comment]
Yes I also don't agree with Metaquotes. There are a lot of changes that can do to make their wrapper better. But unfortunately as I mentioned wrapper should be neat and transparent to the underlying api (man api).

**Comment by Uriil** [comment]
okay, I will leave this discussion and might introduce this change later, because it requires to update all similar cases, which will break backward compatibility

**Comment by miho99** [comment]
You could create extra methods since the signatures are different. In that way you support backward compatibility

**Comment by Uriil** [comment]
Ok, probably you right. But I don't have time now, and will consider it as improvement for future

**Comment by miho99** [comment]
ok

**Comment by miho99** [comment]
Uriil If you could implement a sample one 

virtual int          __stdcall MarginLevelGet(const int login,LPCSTR group,MarginLevel *margin)=0;

I will create the rest

Thanks

**Comment by Uriil** [comment]
Ok, please check on Dev branch, I added overloads for both: HistoryCorrect and MarginLevelGet

**Comment by Uriil** [comment]
Is there any other comments regarding this issue?
