### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Greatsamps** [Uriil/MetaTrader4.Manager.Wrapper#33]
Hi,

We have been using your library and have a feature request. We have written this into our own version based on your source, but would be good to see it in the main release so we can nugget update etc.

This code has been added to the ExtendedPumpingNotify method of ExtendedPumping.cpp

case PUMP_UPDATE_ACTIVATION:
			TradeRecord     *trades;					
			trades = _manager->Manager->TradesGet(&total);
		
			if (trades && total>0)
			{
				for (int i = 0; i<total; i++)
				{
					if (trades[i].activation == ACTIVATION_NONE) continue;
					
					P23::MetaTrader4::Manager::Contracts::TradeRecord^ tr = P23::MetaTrader4::Manager::ClrWrapper::Convert(&trades[i]);
					OrderActivated(this, tr);					
				}
			}
			break;

it caters for a type of pump event that is currently not looked for. We have obviously also created the OrderActivated event, but other than that it is working well.

would you consider adding this?

**Comment by Uriil** [comment]
I would like to keep it close to original mt api as much as possible. Because there is no data for activation request, probably it's not the best place to have this loop here.

However, I can add event for activation with empty args(similar to BidAskUpdated). In this case, you will need to pull your code one level above(place where you subscribing to this event), and everything will be fine for me. What do you think?

**Comment by Greatsamps** [comment]
Hi,

Thanks for your quick response and I respect your goal to keep it as standard as possible!

Your proposed solution would work well and makes sense. 

Kind regards,

**Comment by Uriil** [comment]
Pushed new version please check and let me know if everything fine

**Comment by Greatsamps** [comment]
tested and working well. Thanks for the modification!
