### ISSUE TITLE
The problem on iis

### ISSUE THREAD

**Issue by ilovej** [Uriil/MetaTrader4.Manager.Wrapper#80]
Hello,

I have a problem. When I publish my web application on IIS gives an error.

"Failed to instantiate manager instance"
500 (Internal Server Error)

**Comment by Uriil** [comment]
Do u provide path to mtmanapi.dll explicitly in constructor?

**Comment by ilovej** [comment]
Thank you!
I use by nuget ;
How to  provide path to mtmanapi.dll explicitly in constructor?

**Comment by Uriil** [comment]
Show me, how u create instance of ClrWrapper

**Comment by ilovej** [comment]
https://blogs.msdn.microsoft.com/jorman/2007/08/31/loading-c-assemblies-in-asp-net/
I follow this article to modify  , it work now ;
Is there more better way ?

**Comment by Uriil** [comment]
new ClrWrapper() accepts parameter where u can specify path to mtmanapi.dll, that's how I use it

**Comment by ilovej** [comment]
Oh, I see!
 Thank you very much!

**Comment by ilovej** [comment]
How to use ManageAPI to create an account?
Can you show me a demo?

**Comment by Uriil** [comment]
Due to the fact, that people continue asking me same questions, I think it would be much better to forward such questions to https://stackoverflow.com and tag metatrader4. I am subscribed to this tag and will respond as soon as possible.

So I will appreciate, if you repeat your question there and I will answer there, to keep history

**Comment by ilovej** [comment]
Is that right?
http://stackoverflow.com/questions/39943410/how-to-use-mt4-manageapi-to-create-an-account-and-change-password

**Comment by Uriil** [comment]
Yep, thank you
