### ISSUE TITLE
A question about login timeout

### ISSUE THREAD

**Issue by tangfengray** [Uriil/MetaTrader4.Manager.Wrapper#84]
hi, is there some way to get the login status,like get connected status using the IsConnected function.
i used the Wrapper to make a webservice. but if the manager account is connected but login timeout, the UserRecordsRequest function will return null,even if the user exists.

ClrWrapper man = new ClrWrapper(ConnectionParameters,DllPath);
int login = 123;
Normal：
var list = man.UserRecordsRequest(new List<int> { login });  // result: list.Count == 1;
Abnormal(After a period of time)：
var list = man.UserRecordsRequest(new List<int> { login });  // result: IsConnected()==1;  list.Count == 0;

Hope to get a reply,thanks a lot.

**Comment by Uriil** [comment]
Hi,

I unfortunately no. 
However I might give you some hints, which might help:
1) I think you are getting logged out, because your connection stays idle for some period of time. Try to call Ping command every N seconds
2) you might have some "control" method, like request specific user or something like that
